spring:
  cloud:
    gateway:
      routes:
        - id : rout1
          uri: http://localhost:8081/
          predicates:
            - Path= /customers/**
        - id : rout2
          uri: http://localhost:8082/
          predicates:
            - Path= /products/**
